//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace istanbulakademi_mvcders_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doktor_tbl
    {
        public byte doktorid { get; set; }
        public string doktorad { get; set; }
        public string doktorsoyad { get; set; }
        public string doktorbrans { get; set; }
        public string doktortc { get; set; }
        public string doktorsifre { get; set; }
    }
}
